[project]
name = "group-7-capstone"
version = "0.1.0"
description = "Group 7: Automated Traffic Enforcement in NYC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "pyarrow",
    "duckdb",
    "requests",
    "python-dotenv",
    "geopandas",
    "matplotlib",
]

[dependency-groups]
dev = [
    "pytest",
    "ipykernel",
    "jupyterlab",
    "ruff",
]
